apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-flask
spec:
  selector:
    matchLabels:
      app: k8s-flask
  replicas: 3
  template:
    metadata:
      labels:
        app: k8s-flask
    spec:
      containers:
      - name: k8s-flask
        image: sreenadhtc/flask-hello-world:0.1
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8000
